#!/usr/bin/env bash

# A pipemenu base script/template for creating category based pipemenus
# written by Nathaniel Maia, December 2017 for ArchLabs

# Add something like this to your menu.xml
# <menu execute="SCRIPTNAME" id="NAME" label="PNAME"/>

NAME="terminals"
PNAME="Terminals"
FAIL_MSG="No Apps Installed"

CMD=(terminator tilda tilix urxvt st termite xfce4-terminal xterm)
DESC=(Terminator Tilda Tilix Rxvt-Unicode "Simple Terminal" Termite
      Xfce4-terminal Xterm)

if ! . "/data/data/com.termux/files/usr/lib/archlabs/common/al-include.cfg" 2>/dev/null; then
    echo -e "[ERROR]: Failed to source /data/data/com.termux/files/usr/lib/archlabs/common/al-include.cfg" ; exit 1
fi

menu_Body() {
    for ((i=0; i<${#CMD[@]}; i++)); do
        if hash "${CMD[$i]}" &>/dev/null; then
            menuItem "${DESC[$i]}" "${CMD[$i]}"
        fi
    done
}

menuStart "$NAME" "$PNAME"
for x in "${CMD[@]}"; do
    if hash "$x" &>/dev/null; then
        num=1 ; break
    fi
done
if [[ $num -gt 0 ]]; then
    menu_Body
else
    menuSeparator "$FAIL_MSG"
    if hash pamac-manager &>/dev/null; then
        menuItem "Install with Package Manager" "pamac-manager"
    fi
fi
menuEnd

exit 0
