#!/usr/bin/env bash

count=0
disconnected="ﲁ"
disconnected1="Offline"
wireless_connected="說"
ethernet_connected="說"
connected="Online ﰒ"

#SSID_NAME=$(iwgetid -r)
ID="$(ip link | awk '/state UP/ {print $2}')"

while true; do
    if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 bitbucket.org || ping -c 1 github.com || ping -c 1 sourceforge.net) &>/dev/null; then
        if [[ $ID == e* ]]; then
            echo "$ethernet_connected" ; sleep 25
        else
            echo "$wireless_connected" "$connected"; sleep 5
        fi
    else
        echo "$disconnected" "$disconnected1"; sleep 0.5
    fi
done
