#!/bin/bash

## Author : Aditya Shakya
## Github : adi1090x

# Custom Rofi Script

BORDER="#000000"
SEPARATOR="#000000"
FOREGROUND="#f5f5f5"
BACKGROUND="#000000"
BACKGROUND_ALT="#101010"
HIGHLIGHT_BACKGROUND="#fdd835"
HIGHLIGHT_FOREGROUND="#101010"

BLACK="#000000"
WHITE="#ffffff"
RED="#e53935"
GREEN="#43a047"
YELLOW="#fdd835"
BLUE="#1e88e5"
MAGENTA="#00897b"
CYAN="#00acc1"
PINK="#d81b60"
PURPLE="#8e24aa"
INDIGO="#3949ab"
TEAL="#00897b"
LIME="#c0ca33"
AMBER="#ffb300"
ORANGE="#fb8c00"
BROWN="#6d4c41"
GREY="#757575"
BLUE_GREY="#546e7a"
DEEP_PURPLE="#5e35b1"
DEEP_ORANGE="#f4511e"
LIGHT_BLUE="#039be5"
LIGHT_GREEN="#7cb342"


SDIR="$HOME/.config/polybar/scripts"

# Launch Rofi
MENU="$(rofi -no-lazy-grab -sep "|" -dmenu -i -p 'Style :' \
-hide-scrollbar true \
-bw 0 \
-lines 3 \
-line-padding 8 \
-padding 20 \
-width 20 \
-xoffset 10 -yoffset -33 \
-location 7 \
-columns 3 \
-show-icons -icon-theme "Papirus" \
-font "Noto Sans 9" \
-color-enabled true \
-color-window "$BACKGROUND,$BORDER,$SEPARATOR" \
-color-normal "$BACKGROUND_ALT,$FOREGROUND,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-active "$BACKGROUND,$MAGENTA,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-urgent "$BACKGROUND,$YELLOW,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
<<< " Mode-1| Mode-2| Mode-3| Mode-4| Mode-5| Mode-6")"
            case "$MENU" in
				## Light Colors
				*Mode-1) $SDIR/colors -mode1 ;;
				*Mode-2) $SDIR/colors -mode2 ;;
				*Mode-3) $SDIR/colors -mode3 ;;
				*Mode-4) $SDIR/colors -mode4 ;;
				*Mode-5) $SDIR/colors -mode5 ;;
				*Mode-6) $SDIR/colors -mode6
            esac
